fix: remove duplicates import of ngOvhFeatureFlipping
Fix following error message:
```sh
SyntaxError: Identifier 'ngOvhFeatureFlipping' has already been declared
```

Signed-off-by: Antoine Leblanc <antoine.leblanc@ovhcloud.com>