fix(dashboard.catalog): add missing name attribute (#3618)
Prevent following console error:
```js
Error: oui-field component requires a form control with a name.
```

ref: MANAGER-XMK

Signed-off-by: Antoine Leblanc <antoine.leblanc@ovhcloud.com>